### ISSUE TITLE
Bug: infinite recursion?

### ISSUE THREAD

**Issue by samthomson** [connectedcars/node-logutil#3]
![image](https://user-images.githubusercontent.com/6588340/31764579-7ed596c2-b4b9-11e7-898c-778cde613a24.png)

**Comment by mex** [comment]
We should probably just add
```
if (level > maxNestedDepth) {
  return level
}
```
right after https://github.com/connectedcars/node-logutil/blob/aced433b5819540083b51b7e043eea5fc520a973/src/format.js#L11

**Comment by samthomson** [comment]
closed by https://github.com/connectedcars/node-logutil/pull/4
